#!/usr/bin/env zsh

### Completion
setopt always_to_end auto_name_dirs complete_in_word list_packed

### Expansion and Globbing
setopt bad_pattern brace_ccl extended_glob equals glob_star_short \
       magic_equal_subst rc_expand_param rematch_pcre

### Input/Output
setopt correct mail_warning rc_quotes rm_star_wait short_loops

### History
setopt share_history bang_hist hist_allow_clobber hist_beep \
       hist_expire_dups_first hist_ignore_dups hist_ignore_space hist_no_store \
       hist_reduce_blanks

### Prompting
setopt prompt_sp

### Scripts and Functions
setopt c_bases c_precedences octal_zeroes
