#!/bin/sh

# Disable silver searcher numbers when piped or redirected.
ag() {
  if [[ ! -t 1 ]]; then
    command ag --no-numbers $@
  else
    command ag $@
  fi
}

alias beep='printf "\a"'
alias cargo="noglob cargo"
alias clippy="rustup run nightly cargo clippy"
alias curl="noglob curl"
alias dig="noglob dig"
alias find="noglob find"

fzf_ctrl_t() {
  if git rev-parse >/dev/null 2>&1; then
    git ls-files -co --exclude-standard
  else
    find . | sed 's/^\.\///g'
  fi
}

if command -v hub > /dev/null 2>&1; then
  alias git="noglob hub"
else
  alias git="noglob git"
fi

alias http="noglob http"

if ls --color -d > /dev/null 2>&1; then
  # GNU ls
  alias ls="ls -AF --si --color=auto"
else
  # Other ls, probably BSD
  alias ls="ls -AFh"
fi

if command -v neomutt > /dev/null 2>&1; then
  alias mutt=neomutt
fi

# Define a noglob function for bash that doesn't do anything.
command -v noglob > /dev/null 2>&1 || alias noglob=

alias parachute="devkit parachute"
alias screen="$screen_command"
alias tree="tree -aRF -I .git"
alias tmux='tmux -f "$XDG_CONFIG_HOME/tmux/tmux.conf"'
alias ri="noglob ri"

ruby-install() {
  src_dir="$(mktemp -d -t ruby-install)"
  rubies_dir="$XDG_DATA_HOME/ruby-install/rubies"
  command ruby-install -c -s "$src_dir" -r "$rubies_dir" -j $@
}

alias wget="noglob wget"
alias vim=nvim
