#!/bin/sh

# Disable silver searcher numbers when piped or redirected.
ag() {
  if [[ ! -t 1 ]]; then
    command ag --no-numbers $@
  else
    command ag $@
  fi
}

alias cargo="noglob cargo"
alias clippy="rustup run nightly cargo clippy"
alias curl="noglob curl"
alias dig="noglob dig"
alias dfgit="git --work-tree=$HOME --git-dir=$HOME/code/.dotfiles.git"
alias find="noglob find"
alias http="noglob http"

if command -v hub > /dev/null 2>&1; then
  alias git="noglob hub"
else
  alias git="noglob git"
fi

screen_command="screen -c '\$XDG_CONFIG_HOME/screen/config'"
irssi_command="$screen_command -RR irssi 'command irssi --home \$XDG_CONFIG_HOME/irssi'"
if [[ "$(hostname)" = baltoy.alyssa.is ]]; then
  alias irssi="$irssi_command"
else
  alias irssi="ssh -t alyssa@baltoy.alyssa.is "$irssi_command
fi

if ls --color -d > /dev/null 2>&1; then
  # GNU ls
  alias ls="ls -AF --si --color=auto"
else
  # Other ls, probably BSD
  alias ls="ls -AFh"
fi

# Define a noglob function for bash that doesn't do anything.
command -v noglob > /dev/null 2>&1 || alias noglob=

alias screen="$screen_command"
alias tree="tree -aR -I .git"
alias tmux='tmux -f "$XDG_CONFIG_HOME/tmux/tmux.conf"'
alias ri="noglob ri"
alias ruby-install="ruby-install -c"
alias wget="noglob wget"
alias vim=nvim
