# Highlight any files whose names start with "zsh" as sh
hook global BufCreate (.*/)?\.?zsh.* %{
  set-option buffer filetype sh
}

# Strip trailing whitespace on save
hook global BufWritePre .*(?<!\.diff)$ %{
  execute-keys Z%s\s+$<ret>dz
  echo
}

define-command -docstring "import from the system clipboard" clipboard-import %{
  set-register dquote "%sh{pbpaste}"
  echo -markup "{Information}imported system clipboard to register \""
}

define-command -docstring "export to the system clipboard" clipboard-export %{
  nop %sh{ echo "$kak_reg_dquote" | pbcopy }
  echo -markup "{Information}exported register \" to system clipboard"
}

set global ui_options ncurses_assistant=none
set global autoinfo command|normal

map global normal <a-Y> :clipboard-import<ret>
map global normal <a-y> :clipboard-export<ret>

# Allow indenting from any position in the line, with the correct indentation.
map global insert <tab> '<a-;><a-gt>'
map global insert <backtab> '<a-;><lt>'

set global indentwidth 2
