#!/bin/sh
# Programatically Installing a Terminal theme

set -ue

# 2. Open the theme with Terminal to install it
open -b com.apple.Terminal "$1"

# 3. Close Terminal window
osascript > /dev/null <<OSA
  tell application "Terminal"
    do script "exit" in selected tab of front window
  end tell
OSA

# 4. Set the theme as default:
name="$(basename -s .terminal "$1")"
defaults write com.apple.Terminal "Default Window Settings" "$name"
defaults write com.apple.Terminal "Startup Window Settings" "$name"

echo "Done! Restart Terminal to apply new theme."
