#!/bin/bash

set -ue

cd "$HOME"

# Install dotfiles
git="git --work-tree=$HOME --git-dir=$HOME/dotfiles/.git"
$git checkout .
$git ls-files | grep -v '^\.' | cut -d '/' -f 1 | sort | uniq | xargs rm -r

# Install terminal theme on macOS
if [ "$(uname)" == "Darwin" ]
then

  cd $(mktemp)

  git clone "git@github.com:$STRAP_GITHUB_USER/terminal" .
  "$(basename "$0")"/install_terminal_theme "$STRAP_GITHUB_USER.terminal"

fi

# Set up Sublime Text on macOS
if [ "$(uname)" == "Darwin" ]
then

  local sublime_path="$HOME/Library/Application Support/Sublime Text 3"

  # Install Sublime Package Control
  mkdir -p "$sublime_path/Installed Packages"
  curl "https://packagecontrol.io/Package%20Control.sublime-package" \
    -o "$sublime_path/Installed Packages/Package Control.sublime-package"

  # Set up Sublime user settings.
  mkdir -p "$sublime_path/Packages/User"
  cd "$sublime_path/Packages/User"
  git init
  git remote add origin "git@github.com:$STRAP_GITHUB_USER/sublime-settings"
  git pull

fi

mkdir "$HOME/code"
mv "$HOME/.dotfiles" "$HOME/code/dotfiles"
