#!/bin/bash

set -ue

# Install dotfiles
git="git --work-tree=$HOME --git-dir=$PWD/$(dirname "$0")/../.git"
pushd "$HOME"
$git checkout .
$git ls-files | grep -v '^\.' | cut -d '/' -f 1 | sort | uniq | xargs rm -r
popd

# Install terminal theme on macOS
if [ "$(uname)" == "Darwin" ]
then

  dir="$(mktemp -d)"

  git clone https://github.com/alyssais/terminal.git "$dir"
  "$PWD/$(dirname "$0")"/install_terminal_theme "$dir/alyssais.terminal"

fi

# Set up Sublime Text on macOS
if [ "$(uname)" == "Darwin" ]
then

  sublime_path="$HOME/Library/Application Support/Sublime Text 3"

  # Install Sublime Package Control
  mkdir -p "$sublime_path/Installed Packages"
  curl "https://packagecontrol.io/Package%20Control.sublime-package" \
    -o "$sublime_path/Installed Packages/Package Control.sublime-package"

  # Install Smyck color scheme
  git clone https://github.com/hukl/Smyck-Color-Scheme.git \
    "$sublime_path/Packages/Smyck-Color-Scheme"

  # Set up Sublime user settings.
  mkdir -p "$sublime_path/Packages/User"
  cd "$sublime_path/Packages/User"
  git init
  git remote rm origin || true
  git remote add origin https://github.com/alyssais/sublime-settings.git
  git pull origin master

fi

if ! [ -d "$HOME/code/dotfiles" ]
then
  mkdir "$HOME/code"
  mv "$HOME/.dotfiles/.git" "$HOME/code/.dotfiles.git"
  rm -r "$HOME/.dotfiles"
fi
